Patterns = [

    #word patterns and their replacement
    ('(?<![a-zA-Z])woman(?![a-zA-Z])', 'person'), 
    ('(?<![a-zA-Z])women(?![a-zA-Z])', 'people'), 
    ('(spokeswoman)', "spokesperson"),
    ('(spokeswomen)', "spokesperson"),
    ('(spokesmen)', "spokesperson"),
    ('(spokesman)', "spokesperson"),
    ('(?<![a-zA-Z])congresswoman(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])congresswomen(?![a-zA-Z])', 'people'),
    ('(?<![a-zA-Z])man(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])men(?![a-zA-Z])', 'people'),
    ('(\w+)(man)(\s)', '\\1person\\3'),
    ('(\w+)(woman)(\s)', '\\1person\\3'),
    ('(\w+)(men)(\s)', '\\1people\\3'),
    ('(\w+)(women)(\s)', '\\1people\\3'),
    ('(?<![a-zA-Z])congressman(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])congressmen(?![a-zA-Z])', 'people'),
    ('(?<![a-zA-Z])girl(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])boy(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])girls(?![a-zA-Z])', 'people'),
    ('(?<![a-zA-Z])boys(?![a-zA-Z])', 'people'),
    ('(?<![a-zA-Z])he(?![a-zA-Z])', 'they'),
    ('(?<![a-zA-Z])she(?![a-zA-Z])', 'they'),
    ('(?<![a-zA-Z])his(?![a-zA-Z])', 'their'),
    ('(?<![a-zA-Z])hers(?![a-zA-Z])', 'theirs'),
    ('(?<![a-zA-Z])her(?![a-zA-Z])', 'their'),
    ( '(?<![a-zA-Z])female(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])male(?![a-zA-Z])', ' person'),
    ('(?<![a-zA-Z])mother(?![a-zA-Z])', 'parent'),
    ('(?<![a-zA-Z])mom(?![a-zA-Z])', 'parent'),
    ('(?<![a-zA-Z])father(?![a-zA-Z])', 'parent'),
    ('(?<![a-zA-Z])dad(?![a-zA-Z])', 'parent'),
    ('(?<![a-zA-Z])Vladimir Putin(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Putin(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])queen(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])king(?![a-zA-Z])', 'person'),
    (r'(\([DRrd]-[a-zA-Z]+\))', ''),
    (r'(@[a-zA-Z_-]*)', ''),
    ('(?<![a-zA-Z])Obama(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Trump(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Mcconnell(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Biden(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Sanders(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Barack Obama(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Michelle Obama(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Donald Trump Jr(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Donald Trump(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Melania Trump Jr(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Mitch Mcconnell(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Joe Biden(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Hunter Biden(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Bernie Sanders(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Mitch Mcconnell(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Barack(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Michelle(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Donald(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Melania(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Mitch(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Joe(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Hunter(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Bernie(?![a-zA-Z])', 'person'),
    ('(nytimes.com)', 'news source'),
    ('(cbs.com)', 'news source'),
    ('(abc.com)', 'news source'),
    ('(nbc.com)', 'news source'),
    ('(cnn.com)', 'news source'),
    ('(huffpost.com)', 'news source'),
    ('(breitbart.com)', 'news source'),
    ('(usatoday.com)', 'news source'),
    ('(yahoo.com)', 'news source'),
    ('(fox.com)', 'news source'),
    ('(huffpost.com)', 'news source'),
    ('(breitbart.com)', 'news source'),
    ('(usatoday.com)', 'news source'),
    ('(yahoo.com)', 'news source'),
    ('(fox.com)', 'news source'),
    ('(breitbart)', 'news source'),
    ('(fox)', 'news source'),
    ('(usa today)', 'news source'),
    ('(huffpost)', 'news source'),
    ('(new york times)', 'news source'),
    ('(Yahoo!)', 'norp'),
    ('(breitbart news)', 'news source'),
    ('(fox news)', 'news source'),
    ('(usa today news)', 'news source'),
    ('(huffpost news)', 'news source'),
    ('(huffington post)', 'news source'),
    ('(new york times news)', 'news source'),
    ('(nyt)', 'news source'),
    ('(ABC)', 'news source'),
    ('(NBC)', 'news source'),
    ('(CNN)', 'news source'),
    ('(CBS)', 'news source'),
    ('(\bA.P.)', 'news source'),
    ('(Associated Press)', 'news source'),
    ('(BBC)', 'news source'),
    ('(Netflix)', 'org'),
    ('(NetFlix)', 'org'),
    ('(netflix)', 'org'),
    ('(Georgetown)', 'gpe'),
    ('(GeorgeTown)', 'gpe'),
    ('(georgetown)', 'gpe'),
    ('(SiriusXM)', 'org'),
    ('(amazon)', 'org'),
    ('(Amazon)', 'org'),
    ('(Apple)', 'org'),
    ('(Android)', 'org'),
    ('(netflix)', 'org'),
    ('(Facebook)', 'org'),
    ('(Google)', 'org'),
    ('(Twitter)', 'org'),
    ('( sib-blog )', ''),
    ('(gov\.)', 'governor'),
    ('(Gov\.)', 'governor'),
    ('(Sen\.)', 'senator'),
    ('(sen\.)', 'senator'),
    ('(?<![a-zA-Z])Ocasio-Cortez(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Ocasio Cortez(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Ocasio(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Cortez(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])AOC(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Clinton(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Warren(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Devos(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Palin(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Alexandria Ocasio-Cortez(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Pelosi(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Nancy Pelosi(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Hillary Clinton(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Elizabeth Warren(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Betsy Devos(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Sarah Palin(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Alexandria(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Hillary(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Elizabeth(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Sarah(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])Betsy(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])secretary of state(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])secretary of education(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])department of education(?![a-zA-Z])', 'organization'),
    ('(?<![a-zA-Z])department of state(?![a-zA-Z])', 'organization'),
    ('(?<![a-zA-Z])president of the united states of america(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])president of the united states(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])oval office(?![a-zA-Z])', 'loc'),
    ('(?<![a-zA-Z])president(?![a-zA-Z])', 'person'),
    ('(?<![a-zA-Z])secretary(?![a-zA-Z])', ''),
    ('(?<![a-zA-Z])s(?![a-zA-Z])', ''),
    ('(?<![a-zA-Z])U.S.(?![a-zA-Z])', 'norp'),
    ('(\([DR]-[a-zA-Z.]*\))', ''),
    ('(\b[DR]-[a-zA-Z.]*)', ''),
    ('(\([DRdr]\))', ''),
    ('(Follow)\s[a-zA-Z\s]*Twitter[a-zA-Z\s@]*.', ''),
    ('  ', ' '),

]